"""create automation core tables

Revision ID: e39fe5d914eb
Revises: 580993070075
Create Date: 2026-07-19 13:18:27.194385
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e39fe5d914eb'
down_revision: Union[str, Sequence[str], None] = '580993070075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_schedules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('automation_type', sa.String(length=100), nullable=False),
    sa.Column('contract_version', sa.String(length=20), server_default='1.0', nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('scope_type', sa.Enum('company', 'department', 'location', 'user', name='automation_scope', native_enum=False, create_constraint=True, length=32), server_default='company', nullable=False),
    sa.Column('scope_id', sa.String(length=64), nullable=True),
    sa.Column('schedule_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('recipients', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_automation_schedules_due', 'automation_schedules', ['is_enabled', 'next_run_at'], unique=False)
    op.create_index('ix_automation_schedules_tenant', 'automation_schedules', ['tenant_id', 'automation_type'], unique=False)
    op.create_table('automation_executions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('schedule_id', sa.BigInteger(), nullable=True),
    sa.Column('contract_version', sa.String(length=20), server_default='1.0', nullable=False),
    sa.Column('automation_type', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('pending', 'dispatching', 'running', 'retrying', 'succeeded', 'failed', 'timed_out', 'cancelled', name='automation_execution_status', native_enum=False, create_constraint=True, length=32), server_default='pending', nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='3', nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempt_count >= 0', name='ck_automation_executions_attempt_count'),
    sa.CheckConstraint('max_attempts >= 1', name='ck_automation_executions_max_attempts'),
    sa.ForeignKeyConstraint(['schedule_id'], ['automation_schedules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_executions_execution_id'), 'automation_executions', ['execution_id'], unique=True)
    op.create_index('ix_automation_executions_status_requested', 'automation_executions', ['status', 'requested_at'], unique=False)
    op.create_index('ix_automation_executions_tenant_requested', 'automation_executions', ['tenant_id', 'requested_at'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('contract_version', sa.String(length=20), server_default='1.0', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'published', 'failed', name='outbox_status', native_enum=False, create_constraint=True, length=32), server_default='pending', nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='10', nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=128), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempt_count >= 0', name='ck_outbox_events_attempt_count'),
    sa.CheckConstraint('max_attempts >= 1', name='ck_outbox_events_max_attempts'),
    sa.ForeignKeyConstraint(['execution_id'], ['automation_executions.execution_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_events_event_id'), 'outbox_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_outbox_events_execution_id'), 'outbox_events', ['execution_id'], unique=False)
    op.create_index('ix_outbox_events_pending', 'outbox_events', ['status', 'available_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outbox_events_pending', table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_execution_id'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_event_id'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index('ix_automation_executions_tenant_requested', table_name='automation_executions')
    op.drop_index('ix_automation_executions_status_requested', table_name='automation_executions')
    op.drop_index(op.f('ix_automation_executions_execution_id'), table_name='automation_executions')
    op.drop_table('automation_executions')
    op.drop_index('ix_automation_schedules_tenant', table_name='automation_schedules')
    op.drop_index('ix_automation_schedules_due', table_name='automation_schedules')
    op.drop_table('automation_schedules')
    # ### end Alembic commands ###
