"""Private immutable, product-scoped EOS blobs; no remote URLs or name matching."""
import hashlib
import re
import os
import tempfile
import warnings
from io import BytesIO
from pathlib import Path
from PIL import Image, ImageOps, UnidentifiedImageError
from fastapi import HTTPException
from sqlalchemy import select
from app.models.audit import AuditEvent
from app.core.authorization import product_knowledge_context
from app.product_knowledge import management
from app.product_knowledge.bootstrap import digest

MAX_BYTES = 10 * 1024 * 1024
MAX_PIXELS = 16_000_000
FORMATS = {'image/jpeg': 'JPEG', 'image/png': 'PNG', 'image/webp': 'WEBP'}


def normalize(content, content_type):
    if len(content) > MAX_BYTES:
        raise HTTPException(413, 'Размер фотографии не должен превышать 10 МБ')
    if content_type not in FORMATS:
        raise HTTPException(415, 'Загрузите фотографию JPEG, PNG или WebP')
    try:
        with warnings.catch_warnings():
            warnings.simplefilter('error', Image.DecompressionBombWarning)
            with Image.open(BytesIO(content)) as image:
                if image.format != FORMATS[content_type] or image.width * image.height > MAX_PIXELS or getattr(image, 'n_frames', 1) != 1:
                    raise ValueError('Unsupported image')
                image.verify()
            with Image.open(BytesIO(content)) as image:
                image.load()
                clean = ImageOps.exif_transpose(image).convert('RGB')
                clean.thumbnail((1600, 1600))
                output = BytesIO()
                clean.save(output, format='WEBP', quality=85)
                return output.getvalue()
    except (UnidentifiedImageError, OSError, ValueError, SyntaxError, Image.DecompressionBombError, Image.DecompressionBombWarning) as error:
        raise HTTPException(422, 'Файл повреждён или не является допустимой фотографией') from error


def blob_path(root, product, photo_hash):
    if not re.fullmatch('[a-f0-9]{64}', photo_hash or ''):
        raise HTTPException(404, 'Фотография не найдена')
    # Product UUID is generated by EOS; tenant input is never a filesystem component.
    base = Path(root).resolve()
    path = base / str(product.id) / (photo_hash + '.webp')
    if not path.resolve().is_relative_to(base):
        raise HTTPException(404, 'Фотография не найдена')
    return path


def store(path, content):
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = None
    try:
        with tempfile.NamedTemporaryFile(dir=path.parent, delete=False) as stream:
            temporary = stream.name
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        # Atomic immutable publication, safe for concurrent identical uploads.
        try:
            os.link(temporary, path)
        except FileExistsError:
            if path.read_bytes() != content:
                raise OSError('Blob integrity failure')
        directory = os.open(path.parent, os.O_RDONLY)
        try:
            os.fsync(directory)
        finally:
            os.close(directory)
    finally:
        if temporary is not None:
            os.unlink(temporary)


def mutate(db, user, product_id, command, root, *, content=None, content_type=None):
    context = management.manage_context(db, user)
    product = management.find_product(db, user, product_id, lock=True)
    operation = 'PHOTO_DELETE' if content is None else 'PHOTO_UPLOAD'
    cleaned = normalize(content, content_type) if content is not None else None
    photo_hash = hashlib.sha256(cleaned).hexdigest() if cleaned is not None else None
    command_hash = digest(dict(product_id=str(product.id), operation=operation,
        command=command.model_dump(mode='json'), content_hash=photo_hash))
    if db.scalar(select(AuditEvent.id).where(AuditEvent.tenant_id == user.tenant_id,
        AuditEvent.entity_type == 'ProductKnowledgeProduct', AuditEvent.entity_id == str(product.id),
        AuditEvent.actor_user_id == user.id, AuditEvent.correlation_id == command_hash)):
        return product
    if product.version != command.expected_version:
        raise HTTPException(409, 'Карточка изменена. Обновите её и повторите действие')
    if product.deleted_at:
        raise HTTPException(409, 'Сначала восстановите изделие')
    if cleaned is None and product.local_photo_hash is None:
        raise HTTPException(409, 'У изделия нет локальной фотографии')
    before = management.local_state(product)
    if cleaned is not None:
        try:
            store(blob_path(root, product, photo_hash), cleaned)
        except OSError as error:
            raise HTTPException(503, 'Не удалось сохранить фотографию. Повторите позже') from error
    product.local_photo_hash = photo_hash
    product.version += 1
    management.clear_verification(product)
    management.audit(db, user, context, product, operation, before, command.reason, command_hash)
    return product


def read(db, user, product_id, root):
    product_knowledge_context(db, user)
    product = management.find_product(db, user, product_id)
    path = blob_path(root, product, product.local_photo_hash)
    if not path.is_file():
        raise HTTPException(404, 'Фотография не найдена')
    return path


def verify_storage(db, root):
    """Offline recovery check: current pointers and every retained audit reference."""
    from types import SimpleNamespace
    from app.models.product_knowledge import ProductKnowledgeProduct
    references = set()
    for product in db.scalars(select(ProductKnowledgeProduct).where(ProductKnowledgeProduct.local_photo_hash.is_not(None))):
        references.add((str(product.id), product.local_photo_hash))
    for event in db.scalars(select(AuditEvent).where(AuditEvent.entity_type == 'ProductKnowledgeProduct')):
        for state in (event.before, event.after):
            if state and state.get('local_photo_hash'):
                references.add((event.entity_id, state['local_photo_hash']))
    missing = damaged = 0
    for product_id, photo_hash in references:
        from uuid import UUID
        path = blob_path(root, SimpleNamespace(id=UUID(product_id)), photo_hash)
        if not path.is_file():
            missing += 1
        elif hashlib.sha256(path.read_bytes()).hexdigest() != photo_hash:
            damaged += 1
    return dict(references=len(references), missing=missing, damaged=damaged)


if __name__ == '__main__':
    import sys
    from sqlalchemy.orm import Session
    from sqlalchemy import create_engine
    from app.core.config import settings
    with Session(create_engine(settings.database_url)) as db:
        result = verify_storage(db, settings.product_photo_upload_dir)
    print(result)
    sys.exit(1 if result['missing'] or result['damaged'] else 0)
